name: Trigger Ansible Playbook

on:
  push:
    branches:
      - master  # Change this to your desired deployment branch
  workflow_dispatch:

jobs:
  ansible:
    runs-on: ubuntu-latest  # Use a Linux runner for Ansible compatibility

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Ansible
      run: |
        python -m pip install --upgrade pip
        pip install ansible

    - name: Configure Inventory File
      run: |
        echo "[windows]" > inventory.ini
        echo "${{ EC2_IP }} ansible_user=Administrator ansible_password=${{ EC2_PASSWORD }} ansible_connection=winrm ansible_winrm_transport=basic ansible_port=5986 ansible_winrm_server_cert_validation=ignore" >> inventory.ini

    - name: Run Ansible Playbook
      run: |
        ansible-playbook -i inventory.ini verify_connection.yml
