name: Trigger Ansible Playbook

on:
  push:
    branches:
      - master  # Change this to your desired deployment branch
  workflow_dispatch:

jobs:
  ansible:
    runs-on: windows-latest  # Use a Linux runner for Ansible compatibility

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Ansible
      run: |
        python -m pip install --upgrade pip
        pip install ansible

    - name: Run Ansible Playbook
      run: |
        ansible-playbook -i inventory.ini verify_connection.yml
